# spring.h2.console.enabled=true
# spring.sql.init.platform=h2
# spring.datasource.url=jdbc:h2:mem:discountApp



spring:
  application:
    name: discountApp
  profiles:
    active:
  datasource:
    url: jdbc:h2:mem:discountApp
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
      path: /h2-console
server:
  port: 8081

